# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Vilnius"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm-prod"
      prefix-development: "npm-dev"
    include: "scope"
    labels:
      - "npm dependencies"
    # TODO: Adjust default branch when we will have a branch strategy
    target-branch: "main"

