name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # setup_env:
  #   runs-on: ubuntu-latest
  #   env: 
  #     NODE_ENV: development
  #   steps:
  #     # - name: Checkout
  #     #   uses: actions/checkout@v4

  #     - name: cache node_modules
  #       id: cache-node-modules
  #       uses: actions/cache@v3
  #       with:
  #         path: '**/node_modules'
  #         key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/package-lock.json') }}
      
      
  #     - name: Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
      
  #     - name: Install dependencies
  #       if: steps.cache-node-modules.outputs.cache-hit != 'true'
  #       run: npm install

  # build:
  #   runs-on: ubuntu-latest
  #   env: 
  #     NODE_ENV: development
  #   needs: setup_env
  #   steps:    
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: cache node_modules
  #     id: cache-node-modules
  #     uses: actions/cache@v3
  #     with:
  #       path: '**/node_modules'
  #       key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/package-lock.json') }}

  #   - name: "Build"
  #     run: npm run build

  checkout-and-install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [20.9.0]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin master
      - name: install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: checkout-and-install-dependencies

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        lfs: 'true'
        fetch-depth: 0
    - name: cache node_modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/package-lock.json') }}
    - name: Run test
      uses: actions/checkout@v4
    - name: Run tests
      run: npx jest

  # lint:
  #   runs-on: ubuntu-latest
  #   env: 
  #     NODE_ENV: development
  #   needs: setup_env

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: cache node_modules
  #     id: cache-node-modules
  #     uses: actions/cache@v3
  #     with:
  #       path: '**/node_modules'
  #       key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('**/package-lock.json') }}

  #   - name: Run lint
  #     run: npm run lint
