# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Release
on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types: 
      - completed

jobs:

  create_release_tag:
    runs-on: 'ubuntu-latest'
    outputs:
      get_image_tag_date_timestamp: ${{ steps.get_image_tag_date_timestamp.outputs.date_timestamp }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get image tag date timestamp
      id: get_image_tag_date_timestamp
      run: echo "date_timestamp=$(date '+%F_%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        custom_release_rules: add:minor:Added,remove:minor:Removed,bump:patch:Packages,build:minor:Build,ci:patch:CI,docs:patch:Docs,feat:major:New Features,fix:patch:Fixes,perf:major:Performance optimizations,refactor:patch:Misc Changes,test:patch:Misc Changes,revert:patch:Misc Changes
        custom_tag: ${{ steps.get_image_tag_date_timestamp.outputs.date_timestamp }}
        tag_prefix: deploy_
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    

  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_41bd6a1929b246eb9d49246f19db3ac2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_18aca48b1fca46089adf7fef206f72ae }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_41bd6a1929b246eb9d49246f19db3ac2 }}/vadyba:${{ github.sha }}
        file: ./DOCKERFILE
        context: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vadyba'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1b4ce5c844b94cdda0572d0c5ff40c89 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_41bd6a1929b246eb9d49246f19db3ac2 }}/vadyba:${{ github.sha }}'

  